Repository HackGT/live-site, pull requests merged in 2018-03, with the labels that each got.

#22 Add required files for OneSignal
  OneSignalSDKUpdaterWorker.js
  OneSignalSDKWorker.js
  _config.yml
  _includes/head.html
  manifest.json
Labels: priority / high, status / ready to merge, type / feature

#14 Add blocks and dynamic schedule page
  .gitattributes
  README.md
  _blocks/info.md
  _blocks/links.md
  _blocks/phone_numbers.md
  _config.yml
  _data/navbar_links.yaml
  _event_pages/help.md
  _event_pages/home.md
  _event_pages/home2.md
  _event_pages/map.md
  _event_pages/sample_page.md
  _event_pages/schedule.md
  _includes/footer.html
  _includes/head.html
  _includes/schedule.js
  _layouts/default.html
  _layouts/one_column.html
  _layouts/one_column_schedule.html
  _layouts/page.html
  _layouts/schedule.html
  _layouts/two_column.html
  _sass/block.scss
  _sass/minima.scss
  _sass/minima/_layout.scss
  _sass/schedule.scss
  _sass/site.scss
  assets/fonts/FuturaPTMedium.otf
  assets/fonts/ProximaNovaBold.otf
  assets/fonts/ProximaNovaExtrabold.otf
  assets/fonts/ProximaNovaRegular.otf
  assets/footscript.js
  assets/jquery-3.3.1.min.js
  assets/main.scss
Labels: priority / critical, type / feature

#30 Update manifest.json and add files so the website is kind of a Progressive Web App
  _includes/head.html
  assets/fonts/ProximaNovaBold.otf
  assets/fonts/ProximaNovaExtrabold.otf
  assets/fonts/ProximaNovaRegular.otf
  assets/jquery-3.3.1.min.js
  assets/launcher-icon-1x.png
  assets/launcher-icon-2x.png
  assets/launcher-icon-4x.png
  assets/script.js
  favicon.ico
  manifest.json
Labels: priority / low, type / enhancement

#24 Designing the footer
  .gitignore
  _config.yml
  _includes/footer.html
  _includes/social.html
  _sass/minima/_layout.scss
  deployment.yaml
  manifest.json
Labels: priority / high, status / code review, status / pending changes, type / enhancement
